version: "3.9"

networks:
  chatnet:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    networks: [ chatnet ]

  server:
    build:
      context: ./server
      target: prod
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on: [ redis ]
    expose: [ "3000" ]
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      chatnet:
        aliases: [ api ]

  client:
    build: ./client
    environment:
      - VITE_API_BASE=
    networks: [ chatnet ]
    expose: [ "5173" ]
    restart: unless-stopped

  lb:
    image: nginx:1.25-alpine
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server
      - client
    restart: unless-stopped
    networks: [ chatnet ]
