########### builder stage ###################################
FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

########### runtime #########################################
FROM node:18-alpine

RUN apk add --no-cache nodejs tini

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

ENV REDIS_URL=http://redis:4000
ENV PORT=3000

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "src/index.js"]
